import assert from 'node:assert/strict';
import { chromium } from 'playwright';
import { bootWordPress, phpJson, projectRoot } from '../tools/playground.mjs';
const server = await bootWordPress(9412, false, projectRoot, '7.1.2');
let browser;
try {
  browser = await chromium.launch({ headless: true, channel: 'chrome' });
  const context = await browser.newContext();
  const page = await context.newPage();
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(server.serverUrl);
  assert.equal(await page.locator('#aiwp-consent-panel').isVisible(), false);
  assert.equal((await context.cookies()).filter(c => c.name.startsWith('aiwp_consent')).length, 0);
  await phpJson(server, `
    $s = aiwp_consent_settings(); $s['policy'] = home_url('/privacy/');
    foreach (array('analytics','marketing') as $k) {
      $s[$k] = array('enabled'=>true,'description'=>'Test service '.$k,'js'=>"window.consent_".$k." = true; fetch('/consent-probe?category=".$k."'); document.cookie = '_test_".$k."=yes; Path=/'; localStorage.setItem('_test_".$k."', 'yes');",'cookies'=>'_test_'.$k,'storage'=>'_test_'.$k);
    }
    update_option('aiwp_consent_settings',$s); echo 'true';
  `);
  const probes = [];
  await page.route('**/consent-probe?*', route => { probes.push(route.request().url()); return route.fulfill({ body: 'ok' }); });
  const endpoint = server.serverUrl + '/?aiwp_consent_script=analytics';
  assert.equal((await context.request.get(endpoint)).status(), 403);
  await page.reload();
  await page.locator('#aiwp-consent-panel').waitFor();
  assert.equal(probes.length, 0);
  assert.ok(!(await page.content()).includes('window.consent_analytics'));
  const action = name => page.locator('[data-aiwp-consent-action="' + name + '"]');
  await action('reject').click();
  await page.reload();
  assert.equal(await page.locator('#aiwp-consent-panel').isVisible(), false);
  assert.equal(probes.length, 0);
  await page.locator('[data-aiwp-consent-open]').click();
  await page.locator('[data-aiwp-consent-category="analytics"]').check();
  await action('save').click();
  await page.waitForFunction(() => window.consent_analytics === true);
  assert.equal(await page.evaluate(() => !!window.consent_marketing), false);
  const response = await context.request.get(endpoint);
  assert.equal(response.status(), 200);
  assert.match(response.headers()['cache-control'], /no-store/);
  await page.locator('[data-aiwp-consent-open]').click();
  await Promise.all([page.waitForNavigation(), action('reject').click()]);
  assert.equal(await page.evaluate(() => !!window.consent_analytics), false);
  assert.equal(await page.evaluate(() => localStorage.getItem('_test_analytics')), null);
  assert.equal((await context.cookies()).some(c => c.name === '_test_analytics'), false);
  assert.equal((await context.request.get(endpoint)).status(), 403);
  const preference = (await context.cookies()).find(c => c.name.startsWith('aiwp_consent_'));
  const record = JSON.parse(decodeURIComponent(preference.value));
  record.analytics = true; record.t -= 181 * 86400;
  await context.addCookies([{ ...preference, value: encodeURIComponent(JSON.stringify(record)) }]);
  await page.reload();
  await page.locator('#aiwp-consent-panel').waitFor();
  assert.equal(await page.evaluate(() => !!window.consent_analytics), false);
  assert.equal((await context.request.get(endpoint)).status(), 403);
  await page.setViewportSize({ width: 320, height: 700 });
  assert.ok(await page.locator('#aiwp-consent-panel').evaluate(el => el.scrollWidth <= el.clientWidth));
  await action('accept').click();
  await page.waitForFunction(() => window.consent_analytics && window.consent_marketing);
  const second = await context.newPage();
  await second.route('**/consent-probe?*', route => route.fulfill({ body: 'ok' }));
  await second.goto(server.serverUrl);
  await second.waitForFunction(() => window.consent_analytics && window.consent_marketing);
  await page.locator('[data-aiwp-consent-open]').click();
  await Promise.all([second.waitForNavigation(), page.waitForNavigation(), action('reject').click()]);
  assert.equal(await second.evaluate(() => !!window.consent_analytics), false);
  await second.close();
  await phpJson(server, `
    $s = aiwp_consent_settings(); $s['analytics']['description'] .= ' changed';
    update_option('aiwp_consent_settings',$s); echo 'true';
  `);
  await page.reload();
  await page.locator('#aiwp-consent-panel').waitFor();
  assert.equal(await page.evaluate(() => !!window.consent_analytics), false);
  assert.equal(await phpJson(server, `
    require_once ABSPATH . 'wp-admin/includes/template.php';
    $s = aiwp_consent_settings(); $input = $s;
    $input['analytics']['enabled'] = '1'; $input['marketing']['enabled'] = '1';
    $input['policy'] = ''; $invalid = aiwp_sanitize_consent($input);
    $same = ($invalid === $s);
    wp_set_current_user(0); $denied = aiwp_sanitize_consent($input);
    echo wp_json_encode($same && $denied === $s);
  `), true);
  assert.equal((await context.request.get(server.serverUrl + '/?aiwp_consent_script[]=analytics')).status(), 404);
  await phpJson(server, `wp_set_password('aiwp-local-test',1); echo 'true';`);
  await page.goto(server.serverUrl + '/wp-login.php');
  await page.locator('#user_login').fill('admin');
  await page.locator('#user_pass').fill('aiwp-local-test');
  await Promise.all([page.waitForNavigation(), page.locator('#wp-submit').click()]);
  await page.goto(server.serverUrl + '/wp-admin/admin.php?page=aiwp-consent');
  await page.locator('#aiwp-consent-analytics-description').fill('Updated description from administration');
  await Promise.all([page.waitForNavigation(), page.locator('#submit').click()]);
  assert.equal(await page.locator('#aiwp-consent-analytics-description').inputValue(), 'Updated description from administration');
  assert.equal(await phpJson(server, `echo wp_json_encode(aiwp_consent_settings()['analytics']['enabled']);`), true);
  assert.deepEqual(errors, []);
  console.log('Consent: default off, prior blocking, rejection, selective grant, withdrawal, cleanup, expiry and endpoint checks passed.');
} finally {
  if (browser) await browser.close();
  await server[Symbol.asyncDispose]();
}
