import assert from 'node:assert/strict';
import { chromium } from 'playwright';
import { bootWordPress, phpJson, projectRoot } from '../tools/playground.mjs';
const server = await bootWordPress(9413, false, projectRoot, '7.1.2', null);
let browser;
try {
  const initial = await phpJson(server, `wp_set_password('aiwp-local-test',1); echo wp_json_encode(WSP_Languages::settings());`);
  assert.deepEqual(initial, { ui:'en', public:'en', content:'en' });
  browser = await chromium.launch({ headless:true, channel:'chrome' });
  const page = await browser.newPage();
  page.setDefaultTimeout(20000);
  const errors=[]; page.on('pageerror',e=>errors.push(e.message));
  await page.goto(server.serverUrl+'/wp-login.php');
  await page.locator('#user_login').fill('admin'); await page.locator('#user_pass').fill('aiwp-local-test');
  await Promise.all([page.waitForNavigation(), page.locator('#wp-submit').click()]);
  await page.goto(server.serverUrl+'/wp-admin/admin.php?page=aiwp');
  assert.equal(await page.locator('.aiwp-dashboard h1').innerText(), 'Your website starts with an idea.');
  assert.equal(await page.locator('#toplevel_page_aiwp .wp-menu-name').innerText(), 'ByYourself');
  await page.goto(server.serverUrl+'/wp-admin/post-new.php?post_type=page');
  assert.equal(await page.locator('[data-aiwp-sample]').innerText(),'Insert sample content');
  await page.locator('[data-aiwp-copy-prompt]').click();
  await page.waitForFunction(()=>document.querySelector('[data-aiwp-action-status]').textContent.length > 0);
  assert.match(await page.locator('[data-aiwp-action-status]').innerText(), /Prompt|Copy/);
  await page.goto(server.serverUrl+'/wp-admin/admin.php?page=wsp-languages');
  await page.locator('#wsp-language-ui').selectOption('cs');
  await page.locator('#wsp-language-public').selectOption('cs');
  await Promise.all([page.waitForNavigation(),page.locator('#submit').click()]);
  assert.equal(await page.locator('.wrap h1').last().innerText(),'Jazyk');
  await page.goto(server.serverUrl+'/wp-admin/admin.php?page=aiwp');
  assert.equal(await page.locator('.aiwp-dashboard h1').innerText(),'Váš web začíná nápadem.');
  assert.equal(await page.locator('#toplevel_page_aiwp .wp-menu-name').innerText(), 'ByYourself');
  await page.goto(server.serverUrl+'/wp-admin/post-new.php?post_type=page');
  assert.equal(await page.locator('[data-aiwp-sample]').innerText(),'Vložit ukázkový obsah');
  await page.locator('[data-aiwp-copy-prompt]').click();
  await page.waitForFunction(()=>document.querySelector('[data-aiwp-action-status]').textContent.length > 0);
  assert.match(await page.locator('[data-aiwp-action-status]').innerText(), /Zadání|zadání/);
  await page.goto(server.serverUrl+'/wp-admin/admin.php?page=aiwp-prompts');
  await page.locator('#aiwp-prompt-instructions').fill('Create an accessible contact page.');
  await page.locator('#aiwp-prompt-kind').selectOption('page');
  await page.locator('#aiwp-prompt-generate').click();
  await page.locator('#aiwp-prompt-result').waitFor();
  assert.match(await page.locator('#aiwp-prompt-output').inputValue(), /Požadovaný jazyk obsahu: angličtina/);
  const fixture = await phpJson(server, `
    $id = wp_insert_post(array('post_type'=>'page','post_status'=>'publish','post_title'=>'Keep my title','post_content'=>'Keep my original content'));
    update_post_meta($id, '_aiwp_html', '<section><h1>Do not translate me</h1></section>');
    $s=aiwp_consent_settings(); $s['external']=false; $s['policy']=home_url('/privacy');
    $s['analytics']=array('enabled'=>true,'description'=>'Keep this service description','js'=>'window.languageTestTracking=true;','cookies'=>'','storage'=>'');
    update_option('aiwp_consent_settings',$s); echo wp_json_encode($id);
  `);
  await page.goto(server.serverUrl+'/?page_id='+fixture);
  assert.equal(await page.locator('[data-aiwp-consent-action="accept"]').innerText(),'Přijmout vše');
  await page.goto(server.serverUrl+'/wp-admin/admin.php?page=wsp-languages');
  await page.locator('#wsp-language-public').selectOption('en');
  await Promise.all([page.waitForNavigation(),page.locator('#submit').click()]);
  assert.equal(await page.locator('.wrap h1').last().innerText(),'Jazyk', 'Public language does not change the interface');
  await page.goto(server.serverUrl+'/?page_id='+fixture);
  assert.equal(await page.locator('[data-aiwp-consent-action="accept"]').innerText(),'Accept all');
  assert.equal(await page.locator('.aiwp-consent-description').innerText(),'Keep this service description');
  assert.ok((await page.content()).includes('Keep my original content'));
  await page.goto(server.serverUrl+'/?p=999999');
  assert.equal(await page.locator('main h1').innerText(),'Page not found');
  assert.equal(await phpJson(server, `echo wp_json_encode(get_post_meta(${fixture},'_aiwp_html',true));`), '<section><h1>Do not translate me</h1></section>');
  const protectedSettings = await phpJson(server, `
    require_once ABSPATH . 'wp-admin/includes/template.php';
    wp_set_current_user(1);
    $old=WSP_Languages::settings(); $bad=WSP_Languages::sanitize(array('ui'=>'../../evil','public'=>'en','content'=>'en'));
    wp_set_current_user(0); $denied=WSP_Languages::sanitize(array('ui'=>'en','public'=>'en','content'=>'en'));
    echo wp_json_encode($bad===$old && $denied===$old);
  `);
  assert.equal(protectedSettings,true);
  await phpJson(server, `delete_option('wsp_languages'); echo 'true';`);
  await page.goto(server.serverUrl+'/wp-admin/admin.php?page=wsp-languages');
  assert.equal(await page.locator('#wsp-language-ui').inputValue(),'cs', 'Upgrade preserves Czech on configured sites');
  assert.equal(await phpJson(server, `echo wp_json_encode(get_option('WPLANG',''));`), '', 'WordPress language is unchanged');
  await phpJson(server, `require_once ABSPATH.'wp-admin/includes/plugin.php'; deactivate_plugins('ai-web-studio/ai-web-studio.php'); echo 'true';`);
  await page.goto(server.serverUrl+'/wp-admin/themes.php?page=wsp-languages');
  assert.equal(await page.locator('#wsp-language-ui').inputValue(),'cs', 'Theme supports languages without the plugin');
  await page.locator('#wsp-language-public').selectOption('en');
  await Promise.all([page.waitForNavigation(),page.locator('#submit').click()]);
  await page.goto(server.serverUrl+'/?p=999999');
  assert.equal(await page.locator('main h1').innerText(),'Page not found');
  assert.deepEqual(errors,[]);
  console.log('Languages: defaults, UI/JS/prompts, independent public labels, preserved content, permissions, migration and standalone theme passed.');
} finally { if(browser)await browser.close(); await server[Symbol.asyncDispose](); }
